[package]
name = "aigis_bin"
version = "0.1.0"
authors = ["Emil H. Clausen (SEQUOIIA) <sequoiia@hummel.yt>"]
edition = "2018"

[dependencies]
aigis_lib = {path = "../lib"}
log = "0.4.6"
pretty_env_logger = "0.3"

[[bin]]
name = "aigis-cli"
path = "src/main.rs"
