[package]
name = "aigis_dumper"
version = "0.1.0"
authors = ["Emil H. Clausen (SEQUOIIA) <sequoiia@hummel.yt>"]
edition = "2018"

[dependencies]
log = "0.4.6"
pretty_env_logger = "0.3"
clap = "2.32.0"
aigis_lib = {path = "../../lib"}